version: '3.3'
services:

  db:
  #Specifies the Docker image to use for this service. In this case, 
  #it's using the "postgres:12.0-alpine" image, which is a lightweight PostgreSQL
    image: postgres:12.16-alpine3.18
    container_name: postgres
    #Mounts a volume called "postgres_data" to store the PostgreSQL data files.
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
    #ets environment variables for the PostgreSQL database, 
    #including user, password, database name, and authentication method
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=storedb
      - POSTGRES_HOST_AUTH_METHOD=trust
    expose: 
    #Exposes port 5432 on the container to allow other containers to connect to the PostgreSQL database
      - 5432
    networks:
      - apinetwork

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
    #Maps port 80 from the host to port 8080 on the container, 
    #allowing access to the pgAdmin web interface.
      - "8080:80"
    networks:
      - apinetwork
    links: 
      - db
    depends_on:
      - db

  fastapi:
    container_name: fastapi
    restart: always
    #Specifies the build context and Dockerfile for building the FastAPI application image.
    #image: fastapi:0.0.3
    build:
      context: ./
      dockerfile: Dockerfile
    #name: fastapi-web
    ports:
    #ports: Maps port 5000 from the container to port 80 on the host, 
    #allowing access to the FastAPI application H:C
      - 80:5000
    networks:
      - apinetwork
    depends_on:
      - db
    links: 
      - db
  

volumes:
  postgres_data:

networks:
  apinetwork:
    driver: bridge
