apiVersion: v1
kind: Service
metadata:
  name: {{ include "fastapi.fullname" . }}
  labels:
    {{- include "fastapi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.port }}       
      targetPort: {{ .Values.service.ports.targetPort}}
      name: http
      protocol: TCP
  selector:
    {{- include "fastapi.selectorLabels" . | nindent 4 }}

