apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.pgadmin.name }}
  labels: 
    group: {{ .Values.pgadmin.group }}
spec:
  type: {{ .Values.pgadmin.service.type }}
  selector:             
    app: {{ .Values.pgadmin.name }}
  ports:
      - port: {{ .Values.pgadmin.service.port }}       
        targetPort: {{ .Values.pgadmin.container.port }}   
            
