apiVersion: v1
kind: Service
metadata:
  name: {{ include "pgadmin-runix.fullname" . }}
  labels:
    {{- include "pgadmin-runix.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  port: {{ .Values.service.port }}
  targetPort: {{ .Values.service.targetPort}}
  name: {{ .Values.service.name}}
  protocol: TCP
  selector:
    app: {{ .Values.service.selector }}

